import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import './globals.css'

const font = Raleway({
  subsets: ['latin'], display: "swap",
  
})

export const metadata: Metadata = {
  title: 'My Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  )
}
